name: Build LaTeX document
on:
  push:
    tags:        
      - v**
    branches:
      - main
      - 'release/**'

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/*.ttf
      
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
      
      # Only run the following if a tag was created
      - name: Commit to gh-pages
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git remote update
          git fetch 
          git checkout --track origin/gh-pages
          mv -f main.pdf docs/browningluke-latest.pdf

          git config --global user.email "${{github.event.pusher.email}}"
          git config --global user.name "${{github.event.pusher.name}}"

          git add docs/browningluke-latest.pdf
          git commit -m "${{ github.run_id }}"
          git push
      
      - name: Rename pdf
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cp docs/browningluke-latest.pdf browningluke.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: browningluke.pdf
          fail_on_unmatched_files: true
          generate_release_notes: true
