name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/calibri.ttf
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
      - name: Commit to gh-pages
        run: |
          git remote update
          git fetch 
          git checkout --track gh-pages
          mv -f main.pdf docs/browningluke-latest.pdf
          git add docs/browningluke-latest.pdf
          git commit -m "${{ github.run_id }}"
          git push
